## Informations de connexion à la base de données
database:
  # actually the value 'mysql' is only accepted
  jdbc: mysql
  host: localhost
  database: database
  user: 'user'
  password: 'password'
